name: Pull Request Labeler
on: [pull_request]

jobs:
  label:
    runs-on: ubuntu-latest

    steps:
      - name: Assign PR Labeler
        uses: hi-actions/pr-labeler@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          LABEL_CONFIG_FILE: .github/pr-labeler.yml
