name: deploy-image
on:
  push:
    paths:
      - 'go.mod'
      - '**.go'
      - '**.yml'

jobs:

  # https://docs.github.com/cn/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions
  build-and-push-image:
    runs-on: ubuntu-latest
    # needs: install-deps
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build container image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            docker.pkg.github.com/${{ github.repository_owner }}/${{ github.repository }}:${{ github.sha }}
#            docker.pkg.github.com/${{ github.repository_owner }}/${{ github.repository }}:${{ github.ref }}
            docker.pkg.github.com/${{ github.repository_owner }}/${{ github.repository }}:latest
